### ISSUE TITLE
[feature suggestion] Annotate with repo source when not from CRAN

### ISSUE THREAD

**Issue by jonocarroll** [luisDVA/annotater#1]
One common annotation I add to my `library(pkg)` lines is the GitHub user/repo string which shows where the package can be found, e.g.

```{r}
library(annotater) # luisDVA/annotater
```

This helps the reader to find the package if it is nonstandard.

This could be optionally included in the annotation when the package is installed from GitHub, such as 

```{r}
library(annotater) # [luisDVA/annotater] Annotate Package Load Calls
```

This may be redundant as the repo name is typically (nearly always) the package name, but user/repo is such a common representation that it may still be worthwhile. More complex could be to include the site if this is not GitHub, e.g.

```{r}
library(annotater) # [gitlab::luisDVA/annotater] Annotate Package Load Calls
```

**Comment by luisDVA** [comment]
Hi Jonathan,

I was already playing around with a function and addin to annotate CRAN/non-CRAN packages from the 'Repository'  field returned by  `utils::packageDescription(pkg)`. Your idea is even better.

I should be able to create a  `# [RemoteType::RemoteUsername/RemoteRepo]` annotation for a new function/ addin. I'll push it sometime this week.

Thanks for the feedback!

**Comment by luisDVA** [comment]
Added a function and its respective addin ([commit](https://github.com/luisDVA/annotater/commit/9c9856f722cfe74afde8bd1677c170e864017b42)) to annotate repo sources. Thanks for the suggestion!
