### ISSUE TITLE
feature request: pacman::p_load() in addition to library() and request()

### ISSUE THREAD

**Issue by SchmidtPaul** [luisDVA/annotater#11]
Fantastic idea for a package!! 
However, instead of this:
```r
library(dplyr) # A Grammar of Data Manipulation, CRAN v1.0.7
library(janitor) # Simple Tools for Examining and Cleaning Dirty Data, CRAN v2.1.0
library(naniar) # Data Structures, Summaries, and Visualisations for Missing Data, CRAN v0.6.1
```
I usually go with the [pacman package](https://github.com/trinker/pacman) and I think it would not be too much work to include this somewhere [here in match_pkg_names.R](https://github.com/luisDVA/annotater/blob/ddac95d95987780b5de68927da52ba525b62ba2c/R/match_pkg_names.R#L22)
```r
pacman::p_load(
  dplyr, # A Grammar of Data Manipulation, CRAN v1.0.7
  janitor, # Simple Tools for Examining and Cleaning Dirty Data, CRAN v2.1.0
  naniar # Data Structures, Summaries, and Visualisations for Missing Data, CRAN v0.6.1
)
```
That would be great.

**Comment by luisDVA** [comment]
great idea,
with the growing popularity and use of `pacman` this makes sense. I'll try to implement this soon.

**Comment by SchmidtPaul** [comment]
Hey, am I missing something here? I was happy to see [this tweet of yours](https://twitter.com/LuisDVerde/status/1461524735049834501), but you did not actually push anything to GitHub, right?

**Comment by luisDVA** [comment]
Thanks for reminding me. I'm adding support for `pacman` to the annotation functions one at a time and it was trickier than I anticipated. Will push the updates soon!

**Comment by luisDVA** [comment]
added for v0.2.0!

**Comment by SchmidtPaul** [comment]
Hey, just a minor comment - not sure if it is worthwhile to fix it:

```r
library(annotater)

p_load(
  tidyverse,
  dplyr
)

p_load(tidyverse, dplyr)
```
becomes this
```r
library(annotater) # Annotate Package Load Calls[github::luisDVA/annotater] v0.2.0

p_load(
  tidyverse,
  dplyr
)

p_load(
 tidyverse, # Easily Install and Load the 'Tidyverse' CRAN v1.3.1
 dplyr # A Grammar of Data Manipulation CRAN v1.0.9
 )
```

So one must not have linebreaks in the `p_load()` before using {annotater}.

**Comment by luisDVA** [comment]
thanks for the heads up.
to keep the annotations as non-intrusive as possible I decided to print a message see this [commit](https://github.com/luisDVA/annotater/commit/bdc6022e381deeaa785f300a3290d67ad0816feb) when line breaks are detected inside p_load calls. Will add this to the documentation soon as well.
