### ISSUE TITLE
Tidyverse package and function calls

### ISSUE THREAD

**Issue by RedTent** [luisDVA/annotater#14]
I use a lot of tidyverse functions in my code. The tidyverse package is a "meta-package", which loads a bunch of other packages, like dplyr, stringr and tibble. I use this a lot because it is very convenient. I noticed that the function to annotate package function calls has some trouble handling this and cannot find these functions (see reprex below). 

This is probably an edge case and I do not know if the annotater-package should be able to handle this. But I did at least want to notify you. 

By the way, I really like the package and I'm sure it is gonna be helpful in my work. So thanks for making this package and making it available.

``` r
# Annotate each package function calls
  
library(tidyverse) # "No used functions found" 

mtcars %>% 
  rownames_to_column("cartype") %>% 
  filter(str_detect(cartype, "Mazda"))
#>         cartype mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> 1     Mazda RX4  21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> 2 Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

<sup>Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by luisDVA** [comment]
Thanks for the heads up!
This [issue](https://github.com/luisDVA/annotater/issues/6#issuecomment-651222693) covers your question. `tidyverse` has basically no exported functions of its own, so the function matching methods won't work here. I should make a note of this in the documentation and close this issue once that's done.

**Comment by luisDVA** [comment]
metapackages now addressed in the documentation
