### ISSUE TITLE
[BUG] odd annotation behaviour

### ISSUE THREAD

**Issue by Danny-dK** [luisDVA/annotater#15]
I used your great package often to annotate my script. I installed it somewhere in 2020 (and don't think I ever updated). I recently had to reinstall this package and it seems to have some off behaviour. When commit installed of 2020, no problems. I tried to screen record what happened.

commit ddac95d95987780b5de68927da52ba525b62ba2c in 2020

https://user-images.githubusercontent.com/45395070/183609800-f17e7796-1b8c-4d78-a17e-194004e0d6e3.mp4

latest version

https://user-images.githubusercontent.com/45395070/183609768-f50905b4-65c3-4643-bdc9-9daff93527e2.mp4

In the latest version it seems that a commented line before the library call omits the first library call. Although not shown in the 2020 commit video, this does not happen there (tested it). In addition, the 'annotate titles and repository sources' (the third one down the list) seems to delete 'library()'.

R 4.2.0
Rstudio "Spotted Wakerobin" Release (7872775e, 2022-07-22) for Windows
Windows 10

**Comment by luisDVA** [comment]
thanks for the heads up! I'll look into this weird glitch. I most likely made changes to the matching function and didn't test properly.

**Comment by Danny-dK** [comment]
The removal of `library()` from `annotate titles and repository sources in active file` seems to be caused by [R/annotate_repostitle.R](https://github.com/luisDVA/annotater/blob/d2af624c5152acc80bbeec88e7585a3c54d1fd07/R/annotate_repostitle.R) at line 54

```
 pck_descs$annotated <- paste0(pck_descs$package_name, " # ", pck_descs$title, ", ", pck_descs$annotation, " v", pck_descs$version)
```

Changing `pck_descs$package_name` to `pck_descs$call` seems to solve it (the `call` is also used at Line 93).

**Comment by Danny-dK** [comment]
And for the first line not being annotated, it seems that at [R/match_pkg_names.R](https://github.com/luisDVA/annotater/blob/d2af624c5152acc80bbeec88e7585a3c54d1fd07/R/match_pkg_names.R) at LINE 18

```
lib_matches <- stringr::str_match_all(uncommented_str, stringr::regex("^\\s*?library\\((.*)\\)", multiline = TRUE))
```

The removal of `^\\s*?` seems to solve the issue for me. Perhaps the entire `^\\s*?library\\` is not matched in stringi matches and replaces when plenty of newline characters (`\n`) are present before the first library call. The result of `out_tb` in [R/annotate_repostitle.R](https://github.com/luisDVA/annotater/blob/d2af624c5152acc80bbeec88e7585a3c54d1fd07/R/annotate_repostitle.R) at LINE 18 would result in 

```
# A tibble: 2 × 3
  call                             package_name pkgname_clean
  <chr>                            <chr>        <chr>        
1 "\n\n\n\n\n\n\n\nlibrary(dplyr)" dplyr        dplyr        
2 "library(progress)"              progress     progress   

```


instead of
```
# A tibble: 2 × 3
  call              package_name pkgname_clean
  <chr>             <chr>        <chr>        
1 library(dplyr)    dplyr        dplyr        
2 library(progress) progress     progress    
```
Removal of the `^\\s*?` results in the second table.

Not sure whether it breaks other stuff.

**Comment by luisDVA** [comment]
fixed both issues in the dev version. In one bug the regex was matching newlines and not just horizontal whitespace. The other issue was an error on my part when adding pacman support.
