### ISSUE TITLE
feature request: include source annotation for bioconductor packages

### ISSUE THREAD

**Issue by yanxianl** [luisDVA/annotater#2]
Hi,

The _annotater_ is a really handy tool for loading R packages with annotations.  Thanks you for sharing it!

I just tried it and it worked fine. Below are what I got for my packages after running the RStudio addins. The sources for [CRAN] and [github] packages were given but not for Bioconductor packages _phyloseq_ and _microbiome_. Could you also include source annotations for Bioconductor packages?

```
library(tidyverse) # Easily Install and Load the 'Tidyverse' # [CRAN] 
library(data.table) # Extension of `data.frame` # [CRAN]  
library(qiime2R) # qiime2R # [github::jbisanz/qiime2R] 
library(MicrobeR) # not installed on this machine # [not installed on this machine] 
library(cowplot) # Streamlined Plot Theme and Plot Annotations for 'ggplot2' # [CRAN] 
library(phyloseq) # Handling and analysis of high-throughput microbiome census data 
library(microbiome) # Microbiome Analytics 
library(vegan) # Community Ecology Package # [CRAN]
```
Cheers,
Yanxian

**Comment by luisDVA** [comment]
Hi,
I was planning on adding annotations for bioconductor, gitlab, and bitbucket packges in the near future. The functionality should be ready in the next few weeks. Thanks for the feedback!

**Comment by luisDVA** [comment]
Just upgraded the functions to also annotate packages from Bioconductor. I decided to only add the repository and not the url or repo username because nowadays Bioconductor packages are installed by name using `BiocManager::install()`.
