### ISSUE TITLE
Missing spaces with `pacman::p_load()`

### ISSUE THREAD

**Issue by SchmidtPaul** [luisDVA/annotater#20]
Hey, I just noticed that when I use `Annotate titles and repository sources in active file` on e.g. this

``` r
pacman::p_load(here, tidyverse)
```
it becomes this
``` r
pacman::p_load(
 here, # A Simpler Way to Find Your FilesCRAN v1.0.1
tidyverse # Easily Install and Load the 'Tidyverse'CRAN v1.3.2
 )
```

Which is missing a space (or semicolon?) before the repository sources and also before the tidyverse?

**Comment by luisDVA** [comment]
fixed in the dev version!
