### ISSUE TITLE
Combining package titles and function calls

### ISSUE THREAD

**Issue by roey-angel** [luisDVA/annotater#7]
Hi and thanks for an incredibly useful package!
It would be really helpful to be able to combining two annotation calls through the Addin to be able to annotate both packge title and version and also function calls.

**Comment by luisDVA** [comment]
thank you for using the package and for providing feedback. To keep the annotations as non-invasive as possible, I'm not too keen on combining that many annotations, which often break across lines and may introduce errors when running scripts. I also don't want to saturate people's Addin drop-down with too many functions :man_shrugging: 

At the moment I think the package is broken for some versions of dplyr. Once I get around to fixing that, I'll try out your suggestion and see what happens.
thanks again!

**Comment by Danny-dK** [comment]
I would second the suggestion! Any news on this?

**Comment by luisDVA** [comment]
thanks!
more tests on this confirmed by suspicion that long titles + versions + function calls become too long and break across lines in the source pane, leading to errors when running code. I don't want to introduce errors this way, so will be looking into maybe pasting the title and version plus the function calls in a commented box (see LittleBoxes) below each `library`  call. More on this soon
