### ISSUE TITLE
feature request: allowing RMarkdown to annotate functions used in packages.

### ISSUE THREAD

**Issue by Greenwind1** [luisDVA/annotater#8]
Hi, Thank you for developing a nice package.

I am currently using the below annotation feature for functions used in the package.  
  
![](https://raw.githubusercontent.com/luisdva/annotater/master/inst/media/jcruz.gif)

It would be great if this very useful feature could also be used in `RMarkdown` 😃
Do you have any plans for that?

**Comment by luisDVA** [comment]
Thanks for the feedback!
This function was contributed by @jcrodriguez1989, let's see if he can figure out why this function isn't running on Rmd files. Otherwise I'll look into it. cheers

**Comment by luisDVA** [comment]
finally working on this issue it looks like a problem with the backticks that delimit code blocks in Rmd files and how they throw errors when trying to parse the scripts using `base::parse`. Will look for a workaround at some point in the near future.

**Comment by kenneditodd** [comment]
Hi @luisDVA,

Has any workaround been found?

**Comment by luisDVA** [comment]
Hi! 
I've looked into this briefly because I'm interested in rmd and qmd compatibility. I made some progress and will try to pick this up again next month after some travel.

**Comment by jcrodriguez1989** [comment]
Hi @luisDVA , sorry for the long time without a reply.
This year I have some time to participate in [Hacktoberfest](https://hacktoberfest.com/participation/), would you mind adding the “hacktoberfest” topic to this repo?
I can take a look at this issue, and any other issue you think is relevant.

**Comment by luisDVA** [comment]
added the topic to the repo now!
